const std = @import("std");
const plan_mod = @import("plan.zig");
const InstallPlan = plan_mod.InstallPlan;
const SystemctlUserPlan = plan_mod.SystemctlUserPlan;
const writeAll = plan_mod.writeAll;
const ensureDirAll = plan_mod.ensureDirAll;
const runCmd = plan_mod.runCmd;
const runCmdWarn = plan_mod.runCmdWarn;
const planSystemctlUser = plan_mod.planSystemctlUser;
const atomicInstallBinary = plan_mod.atomicInstallBinary;

pub const SystemctlScope = enum { system, user, both };

/// Test hook: when non-null, `stopDaemonScope` records calls here instead of
/// invoking real systemctl. Set to a non-null pointer in tests; reset to null
/// in `defer`. Each call appends the scope and verbs (verbs are not duped).
pub const TestStopCall = struct { scope: SystemctlScope, verbs: []const []const u8 };
pub var test_stop_calls: ?*std.ArrayList(TestStopCall) = null;
/// Test hook: when non-null, `stopDaemonScope` returns this error before
/// dispatching to systemctl. Lets tests simulate a failed stop.
pub var test_stop_force_error: ?anyerror = null;

/// Generate the systemd --user unit. SupplementaryGroups= is intentionally
/// NOT emitted: a user-scope service manager runs unprivileged (no CAP_SETGID)
/// and cannot apply it, so the directive aborts startup with status=216/GROUP
/// regardless of whether the host has an 'input' group (issues #287, #288).
/// Device-node access for the daemon comes from udev GROUP="input" MODE="0660"
/// rules plus desktop uaccess ACLs, not from the unit.
pub fn generateServiceContent(allocator: std.mem.Allocator, prefix: []const u8) ![]const u8 {
    const exec_start = if (std.mem.eql(u8, prefix, "/usr"))
        try std.fmt.allocPrint(allocator, "{s}/bin/padctl", .{prefix})
    else
        try std.fmt.allocPrint(allocator, "{s}/bin/padctl --config-dir {s}/share/padctl/devices", .{ prefix, prefix });
    defer allocator.free(exec_start);

    return std.fmt.allocPrint(allocator,
        \\[Unit]
        \\Description=padctl gamepad compatibility daemon
        \\After=graphical-session.target
        \\
        \\[Service]
        \\Type=simple
        \\ExecStart={s}
        \\Restart=on-failure
        \\RestartSec=3
        \\# Pin the IPC socket to the per-user runtime dir (%t = $XDG_RUNTIME_DIR
        \\# for user units). PADCTL_SOCKET is the top-precedence override in
        \\# resolveSocketPath, so the daemon never falls back to the root-owned
        \\# /run/padctl — which the immutable drop-in renders read-only (only the
        \\# runtime dir is writable there). Without this, a stale advertised file
        \\# under /run/padctl (or an empty /run/padctl created root-owned by
        \\# padctl-reconnect) makes bind fail with AddressInUse/EROFS and the
        \\# daemon runs with no control socket, silently breaking
        \\# `padctl status`/`switch`/`devices`.
        \\Environment=PADCTL_SOCKET=%t/padctl.sock
        \\# Canonical state/log dir: $XDG_STATE_HOME/padctl on user services,
        \\# /var/lib/padctl on system services. systemd pre-creates it with
        \\# the right perms, exports $STATE_DIRECTORY, and auto-whitelists
        \\# the path through read-only home/system protections applied via
        \\# drop-ins so the daemon can always write its dump log there.
        \\StateDirectory=padctl
        \\
        \\[Install]
        \\WantedBy=default.target
        \\
    , .{exec_start});
}

pub const immutable_dropin_content =
    \\[Service]
    \\# Reset device allowlist — the base service restricts to hidraw+uinput+input,
    \\# but libusb needs broader access to USB bus device nodes (/dev/bus/usb/) for
    \\# vendor-specific control transfers (init commands, rumble, LED control).
    \\# Bare DeviceAllow= clears the list; with no further entries, cgroup device
    \\# controller falls back to allowing all device access.
    \\DeviceAllow=
    \\# Allow reading user mapping configs from ~/.config/padctl/.
    \\# ProtectHome=read-only also covers /run/user/%U per systemd.exec(5),
    \\# so we must punch a hole for the daemon's IPC socket below.
    \\ProtectHome=read-only
    \\# ProtectHome=read-only locks /run/user/%U, which would otherwise make
    \\# the daemon's $XDG_RUNTIME_DIR/padctl.sock bind fail with EROFS and
    \\# silently break `padctl status`/`switch`/`devices`. Grant write access
    \\# back to just the runtime dir without loosening the $HOME protection.
    \\ReadWritePaths=/run/user/%U
    \\# Short timeout for processes stuck in uninterruptible I/O
    \\TimeoutStopSec=3
    \\# SIGTERM main + SIGKILL stuck threads simultaneously
    \\KillMode=mixed
    \\
;

pub fn generateReconnectScript(allocator: std.mem.Allocator, prefix: []const u8) ![]const u8 {
    return std.fmt.allocPrint(allocator,
        \\#!/bin/bash
        \\# padctl-reconnect — safe hotplug handler for padctl
        \\# Auto-generated by padctl install — do not edit
        \\#
        \\# On device add: re-applies mapping via running daemon socket.
        \\# The daemon must already be running (enabled via: padctl install).
        \\mkdir -p /run/padctl
        \\exec 200>/run/padctl/padctl-reconnect.lock
        \\flock -n 200 || exit 0
        \\
        \\sleep 1
        \\
        \\# Re-apply mapping after hotplug (device reconnects in passthrough mode).
        \\# Prefer config.toml's default_mapping; fall back to explicit mapping files.
        \\# /etc/padctl/mappings is the FHS sysconfdir — fixed at /etc regardless
        \\# of --prefix. systemConfigDir() in src/config/paths.zig is the SSOT.
        \\sleep 2
        \\padctl_bin="{s}/bin/padctl"
        \\
        \\run_padctl_switch() {{
        \\    local sock="$1"
        \\    shift
        \\
        \\    if [[ "$sock" == /run/user/*/padctl.sock ]]; then
        \\        local uid passwd user home
        \\        uid="$(stat -c %u "$sock" 2>/dev/null)" || return 1
        \\        passwd="$(getent passwd "$uid")" || return 1
        \\        IFS=: read -r user _ _ _ _ home _ <<< "$passwd"
        \\        [ -n "$user" ] && [ -n "$home" ] || return 1
        \\        command -v runuser >/dev/null 2>&1 || return 1
        \\        runuser -u "$user" -- env -u XDG_CONFIG_HOME HOME="$home" USER="$user" LOGNAME="$user" XDG_RUNTIME_DIR="/run/user/$uid" "$padctl_bin" switch "$@" --socket "$sock"
        \\        return $?
        \\    fi
        \\
        \\    "$padctl_bin" switch "$@" --socket "$sock"
        \\}}
        \\
        \\sockets=()
        \\for sock in /run/user/*/padctl.sock; do
        \\    [ -S "$sock" ] && sockets+=("$sock")
        \\done
        \\[ -S /run/padctl/padctl.sock ] && sockets+=("/run/padctl/padctl.sock")
        \\[ ${{#sockets[@]}} -eq 0 ] && exit 0
        \\
        \\fallback_mapping=""
        \\for f in $(ls /etc/padctl/mappings/*.toml 2>/dev/null | sort); do
        \\    [ -f "$f" ] || continue
        \\    fallback_mapping="$f"
        \\    break
        \\done
        \\
        \\applied=0
        \\for sock in "${{sockets[@]}}"; do
        \\    run_padctl_switch "$sock" 2>/dev/null && applied=1 && continue
        \\    [ -n "$fallback_mapping" ] || continue
        \\    run_padctl_switch "$sock" "$fallback_mapping" 2>/dev/null && applied=1
        \\done
        \\
    , .{prefix});
}

/// Generate the udev RUN+= launcher. udev kills the control group it creates
/// for the event once the rule handler returns, so padctl-reconnect must be
/// detached to survive that. Checking for a live systemd PID 1 (rather than
/// `command -v systemd-run`) matters because some non-systemd distros still
/// ship the binary; on those hosts `setsid` is the fallback that actually
/// detaches the process.
pub fn generateReconnectLaunchScript(allocator: std.mem.Allocator, prefix: []const u8) ![]const u8 {
    return std.fmt.allocPrint(allocator,
        \\#!/bin/sh
        \\# padctl-reconnect-launch — Auto-generated by padctl install — do not edit
        \\if [ -d /run/systemd/system ]; then
        \\    exec /usr/bin/systemd-run --no-block {s}/bin/padctl-reconnect
        \\fi
        \\setsid {s}/bin/padctl-reconnect </dev/null >/dev/null 2>&1 &
        \\
    , .{ prefix, prefix });
}

/// Generate the system service content matching the legacy format but with
/// correct ExecStart for the given prefix.
pub fn generateSystemServiceContent(allocator: std.mem.Allocator, prefix: []const u8, has_input_group: bool) ![]const u8 {
    const exec_start = if (std.mem.eql(u8, prefix, "/usr"))
        try std.fmt.allocPrint(allocator, "{s}/bin/padctl", .{prefix})
    else
        try std.fmt.allocPrint(allocator, "{s}/bin/padctl --config-dir {s}/share/padctl/devices", .{ prefix, prefix });
    defer allocator.free(exec_start);

    const group_line: []const u8 = if (has_input_group) "SupplementaryGroups=input\n" else "";

    return std.fmt.allocPrint(allocator,
        \\[Unit]
        \\Description=padctl gamepad compatibility daemon
        \\After=local-fs.target
        \\
        \\[Service]
        \\Type=simple
        \\ExecStart={s}
        \\Restart=on-failure
        \\RestartSec=3
        \\ProtectSystem=strict
        \\ProtectHome=true
        \\PrivateTmp=true
        \\RuntimeDirectory=padctl
        \\RuntimeDirectoryMode=0755
        \\RuntimeDirectoryPreserve=no
        \\StateDirectory=padctl
        \\{s}DeviceAllow=/dev/hidraw* rw
        \\DeviceAllow=/dev/uinput rw
        \\DeviceAllow=/dev/uhid rw
        \\DeviceAllow=char-input rw
        \\
        \\[Install]
        \\WantedBy=multi-user.target
        \\
    , .{ exec_start, group_line });
}

/// Update any legacy system service files left behind by pre-user-service
/// installs. Without this, upgrades leave stale ExecStart (missing
/// --config-dir) and stale drop-ins on disk; if a user later re-enables
/// the legacy unit manually, they would get the old stale content.
pub fn updateLegacySystemService(allocator: std.mem.Allocator, destdir: []const u8, prefix: []const u8, has_input_group: bool) void {
    const etc_dir = std.fmt.allocPrint(allocator, "{s}/etc/systemd/system", .{destdir}) catch return;
    defer allocator.free(etc_dir);
    updateLegacyAt(allocator, prefix, etc_dir, has_input_group);

    const lib_dir = std.fmt.allocPrint(allocator, "{s}{s}/lib/systemd/system", .{ destdir, prefix }) catch return;
    defer allocator.free(lib_dir);
    updateLegacyAt(allocator, prefix, lib_dir, has_input_group);
}

pub fn updateLegacyAt(
    allocator: std.mem.Allocator,
    prefix: []const u8,
    base_dir: []const u8,
    has_input_group: bool,
) void {
    const svc_path = std.fmt.allocPrint(allocator, "{s}/padctl.service", .{base_dir}) catch return;
    defer allocator.free(svc_path);
    if (std.fs.accessAbsolute(svc_path, .{})) {
        const content = generateSystemServiceContent(allocator, prefix, has_input_group) catch return;
        defer allocator.free(content);
        if (std.fs.createFileAbsolute(svc_path, .{ .truncate = true })) |f| {
            defer f.close();
            f.writeAll(content) catch return;
            _ = std.posix.write(std.posix.STDOUT_FILENO, "  ") catch {};
            _ = std.posix.write(std.posix.STDOUT_FILENO, svc_path) catch {};
            _ = std.posix.write(std.posix.STDOUT_FILENO, " (legacy update)\n") catch {};
        } else |_| {}
    } else |_| {}

    // Refresh immutable.conf only when it already exists. Earlier the check
    // guarded on padctl.service.d/ existence, which would spawn a fresh
    // immutable.conf inside directories that happened to contain unrelated
    // user-owned drop-ins — introducing an override the user never asked for.
    const dropin_dir = std.fmt.allocPrint(allocator, "{s}/padctl.service.d", .{base_dir}) catch return;
    defer allocator.free(dropin_dir);
    const dropin_path = std.fmt.allocPrint(allocator, "{s}/immutable.conf", .{dropin_dir}) catch return;
    defer allocator.free(dropin_path);
    if (std.fs.accessAbsolute(dropin_path, .{})) {
        if (std.fs.createFileAbsolute(dropin_path, .{ .truncate = true })) |f| {
            defer f.close();
            f.writeAll(immutable_dropin_content) catch return;
            _ = std.posix.write(std.posix.STDOUT_FILENO, "  ") catch {};
            _ = std.posix.write(std.posix.STDOUT_FILENO, dropin_path) catch {};
            _ = std.posix.write(std.posix.STDOUT_FILENO, " (legacy update)\n") catch {};
        } else |_| {}
    } else |_| {}
}

pub fn freeArgv(allocator: std.mem.Allocator, argv: [][]const u8) void {
    for (argv) |s| allocator.free(s);
    allocator.free(argv);
}

/// Build argv for invoking `systemctl --user <verbs...>` under the correct bus.
/// Caller owns the returned slice and each nested string via the allocator.
///
/// sudo_hop form:
///   sudo -u <USER> XDG_RUNTIME_DIR=/run/user/<UID> \
///        DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/<UID>/bus \
///        systemctl --user <verbs...>
pub fn buildSystemctlUserArgv(
    allocator: std.mem.Allocator,
    plan: SystemctlUserPlan,
    verbs: []const []const u8,
) !?[][]const u8 {
    if (plan.mode == .skip) return null;

    var argv = std.ArrayList([]const u8){};
    errdefer {
        for (argv.items) |s| allocator.free(s);
        argv.deinit(allocator);
    }

    if (plan.mode == .sudo_hop) {
        try argv.append(allocator, try allocator.dupe(u8, "sudo"));
        try argv.append(allocator, try allocator.dupe(u8, "-u"));
        try argv.append(allocator, try allocator.dupe(u8, plan.sudo_user));
        const xrd = try std.fmt.allocPrint(allocator, "XDG_RUNTIME_DIR=/run/user/{s}", .{plan.sudo_uid});
        try argv.append(allocator, xrd);
        const dbus = try std.fmt.allocPrint(allocator, "DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/{s}/bus", .{plan.sudo_uid});
        try argv.append(allocator, dbus);
    }
    try argv.append(allocator, try allocator.dupe(u8, "systemctl"));
    try argv.append(allocator, try allocator.dupe(u8, "--user"));
    for (verbs) |v| try argv.append(allocator, try allocator.dupe(u8, v));

    return try argv.toOwnedSlice(allocator);
}

pub fn currentPlanFromEnv() SystemctlUserPlan {
    const uid = std.os.linux.getuid();
    const sudo_user = std.posix.getenv("SUDO_USER");
    const sudo_uid = std.posix.getenv("SUDO_UID");
    return planSystemctlUser(uid, sudo_user, sudo_uid);
}

pub fn printSkipSystemctlNote() void {
    // Default hint used by the thin helpers — the install/uninstall call sites
    // dedupe via `printSkipSystemctlNoteFor` so the user only sees a single
    // 4-line note per phase. This fallback covers defensive callers.
    const default_verbs = [_][]const []const u8{
        &.{"daemon-reload"},
        &.{ "enable", "--now", "padctl.service" },
    };
    printSkipSystemctlNoteFor(&default_verbs);
}

/// Variant that reflects the actual set of verb groups that were skipped.
pub fn printSkipSystemctlNoteFor(verb_groups: []const []const []const u8) void {
    writeAll(
        std.posix.STDERR_FILENO,
        "note: skipping `systemctl --user` — running as root without SUDO_USER; as your real user run:\n",
    );
    for (verb_groups) |verbs| {
        writeAll(std.posix.STDERR_FILENO, "  systemctl --user");
        for (verbs) |v| {
            writeAll(std.posix.STDERR_FILENO, " ");
            writeAll(std.posix.STDERR_FILENO, v);
        }
        writeAll(std.posix.STDERR_FILENO, "\n");
    }
}

/// Thin wrapper over buildSystemctlUserArgv + runCmd. Mirrors runCmd semantics (silent on non-zero).
pub fn runSystemctlUser(verbs: []const []const u8) void {
    const plan = currentPlanFromEnv();
    if (plan.mode == .skip) {
        printSkipSystemctlNote();
        return;
    }
    const allocator = std.heap.page_allocator;
    const argv = buildSystemctlUserArgv(allocator, plan, verbs) catch |err| {
        var errbuf: [128]u8 = undefined;
        const msg = std.fmt.bufPrint(&errbuf, "warning: could not build systemctl argv: {}\n", .{err}) catch "warning: systemctl argv build failed\n";
        writeAll(std.posix.STDERR_FILENO, msg);
        return;
    } orelse {
        printSkipSystemctlNote();
        return;
    };
    defer freeArgv(allocator, argv);
    runCmd(argv);
}

/// Same as runSystemctlUser but warns on non-zero exit (mirrors runCmdWarn).
/// Returns true when systemctl ran and exited 0 (the user bus was reachable and
/// the verb succeeded), false when it was skipped, could not be built, or the
/// user manager rejected the command (bus not live — headless/boot-before-login).
pub fn runSystemctlUserWarn(verbs: []const []const u8) bool {
    const plan = currentPlanFromEnv();
    if (plan.mode == .skip) {
        printSkipSystemctlNote();
        return false;
    }
    const allocator = std.heap.page_allocator;
    const argv = buildSystemctlUserArgv(allocator, plan, verbs) catch |err| {
        var errbuf: [128]u8 = undefined;
        const msg = std.fmt.bufPrint(&errbuf, "warning: could not build systemctl argv: {}\n", .{err}) catch "warning: systemctl argv build failed\n";
        writeAll(std.posix.STDERR_FILENO, msg);
        return false;
    } orelse {
        printSkipSystemctlNote();
        return false;
    };
    defer freeArgv(allocator, argv);
    return runCmdWarn(argv);
}

/// System-scope counterpart to runSystemctlUser. Used by the legacy-unit
/// migration path on /etc/systemd/system/padctl.service.
pub fn runSystemctlSystem(verbs: []const []const u8) void {
    const allocator = std.heap.page_allocator;
    const argv = buildSystemctlSystemArgv(allocator, verbs) catch |err| {
        var errbuf: [128]u8 = undefined;
        const msg = std.fmt.bufPrint(&errbuf, "warning: could not build systemctl argv: {}\n", .{err}) catch "warning: systemctl argv build failed\n";
        writeAll(std.posix.STDERR_FILENO, msg);
        return;
    };
    defer freeArgv(allocator, argv);
    runCmd(argv);
}

/// Stop the padctl service in the requested systemctl scope(s) before any
/// destructive op on daemon-owned runtime state (issue #216). On `.both`,
/// stops are dispatched to both system and user scopes; either may report
/// "not loaded" / "inactive" without surfacing as an error — the caller
/// re-probes the socket afterwards to confirm the daemon released it.
pub fn stopDaemonScope(allocator: std.mem.Allocator, scope: SystemctlScope) !void {
    if (test_stop_force_error) |err| return err;
    if (test_stop_calls) |list| {
        try list.append(allocator, .{ .scope = scope, .verbs = &.{ "stop", "padctl.service" } });
        return;
    }
    switch (scope) {
        .system => runSystemctlSystem(&.{ "stop", "padctl.service" }),
        .user => runSystemctlUser(&.{ "stop", "padctl.service" }),
        .both => {
            runSystemctlSystem(&.{ "stop", "padctl.service" });
            runSystemctlUser(&.{ "stop", "padctl.service" });
        },
    }
}

fn buildSystemctlSystemArgv(allocator: std.mem.Allocator, verbs: []const []const u8) ![][]const u8 {
    var argv = try allocator.alloc([]const u8, 1 + verbs.len);
    var filled: usize = 0;
    errdefer {
        for (argv[0..filled]) |s| allocator.free(s);
        allocator.free(argv);
    }
    argv[0] = try allocator.dupe(u8, "systemctl");
    filled = 1;
    for (verbs, 0..) |v, i| {
        argv[1 + i] = try allocator.dupe(u8, v);
        filled = 2 + i;
    }
    return argv;
}

pub fn installBinaries(
    allocator: std.mem.Allocator,
    plan: *const InstallPlan,
    self_path: []const u8,
    self_dir: []const u8,
) !void {
    const bin_padctl = try std.fmt.allocPrint(allocator, "{s}/padctl", .{plan.bin_dir});
    defer allocator.free(bin_padctl);
    try atomicInstallBinary(allocator, self_path, bin_padctl);
    _ = std.posix.write(std.posix.STDOUT_FILENO, "  ") catch {};
    _ = std.posix.write(std.posix.STDOUT_FILENO, bin_padctl) catch {};
    _ = std.posix.write(std.posix.STDOUT_FILENO, "\n") catch {};

    for ([_][]const u8{ "padctl-capture", "padctl-debug" }) |name| {
        const src = try std.fmt.allocPrint(allocator, "{s}/{s}", .{ self_dir, name });
        defer allocator.free(src);
        const dst = try std.fmt.allocPrint(allocator, "{s}/{s}", .{ plan.bin_dir, name });
        defer allocator.free(dst);
        atomicInstallBinary(allocator, src, dst) catch continue;
        _ = std.posix.write(std.posix.STDOUT_FILENO, "  ") catch {};
        _ = std.posix.write(std.posix.STDOUT_FILENO, dst) catch {};
        _ = std.posix.write(std.posix.STDOUT_FILENO, "\n") catch {};
    }
}

pub fn installServiceFiles(allocator: std.mem.Allocator, plan: *const InstallPlan) !void {
    const service_path = try std.fmt.allocPrint(allocator, "{s}/padctl.service", .{plan.service_dir});
    defer allocator.free(service_path);
    // Always use the user-service template. Even on immutable-root installs,
    // the service file is placed under /etc/systemd/user/ so systemd discovers
    // it as a user unit and each user's systemd instance runs its own copy.
    const service_content = try generateServiceContent(allocator, plan.prefix);
    defer allocator.free(service_content);
    {
        var f = try std.fs.createFileAbsolute(service_path, .{ .truncate = true });
        defer f.close();
        try f.writeAll(service_content);
    }
    _ = std.posix.write(std.posix.STDOUT_FILENO, "  ") catch {};
    _ = std.posix.write(std.posix.STDOUT_FILENO, service_path) catch {};
    _ = std.posix.write(std.posix.STDOUT_FILENO, "\n") catch {};

    if (plan.effective_immutable) {
        const dropin_dir = try std.fmt.allocPrint(allocator, "{s}/padctl.service.d", .{plan.service_dir});
        defer allocator.free(dropin_dir);
        try ensureDirAll(allocator, dropin_dir);
        const dropin_path = try std.fmt.allocPrint(allocator, "{s}/immutable.conf", .{dropin_dir});
        defer allocator.free(dropin_path);
        {
            var f = try std.fs.createFileAbsolute(dropin_path, .{ .truncate = true });
            defer f.close();
            try f.writeAll(immutable_dropin_content);
        }
        _ = std.posix.write(std.posix.STDOUT_FILENO, "  ") catch {};
        _ = std.posix.write(std.posix.STDOUT_FILENO, dropin_path) catch {};
        _ = std.posix.write(std.posix.STDOUT_FILENO, "\n") catch {};
    }

    // Refresh any legacy system service drop-in if it exists, regardless
    // of effective_immutable. Pre-user-service installs on any distro
    // placed the unit under /etc/systemd/system/ or <prefix>/lib/systemd/
    // system/. The helper is a no-op when no legacy file is present.
    // SupplementaryGroups= remains valid on a system-scope unit (PID 1 has
    // CAP_SETGID), so the legacy path keeps the conditional probe.
    updateLegacySystemService(allocator, plan.opts.destdir, plan.prefix, plan_mod.hostHasInputGroup());
}

pub fn installExecutableScript(path: []const u8, content: []const u8, warn_msg: []const u8) !void {
    {
        var f = try std.fs.createFileAbsolute(path, .{ .truncate = true });
        defer f.close();
        try f.writeAll(content);
    }
    std.posix.fchmodat(std.fs.cwd().fd, path, 0o755, 0) catch {
        _ = std.posix.write(std.posix.STDERR_FILENO, warn_msg) catch {};
    };
    _ = std.posix.write(std.posix.STDOUT_FILENO, "  ") catch {};
    _ = std.posix.write(std.posix.STDOUT_FILENO, path) catch {};
    _ = std.posix.write(std.posix.STDOUT_FILENO, "\n") catch {};
}

pub fn installReconnectScript(allocator: std.mem.Allocator, plan: *const InstallPlan) !void {
    const reconnect_script = try generateReconnectScript(allocator, plan.prefix);
    defer allocator.free(reconnect_script);
    const reconnect_path = try std.fmt.allocPrint(allocator, "{s}/padctl-reconnect", .{plan.bin_dir});
    defer allocator.free(reconnect_path);
    try installExecutableScript(reconnect_path, reconnect_script, "warning: could not chmod padctl-reconnect\n");

    const launch_script = try generateReconnectLaunchScript(allocator, plan.prefix);
    defer allocator.free(launch_script);
    const launch_path = try std.fmt.allocPrint(allocator, "{s}/padctl-reconnect-launch", .{plan.bin_dir});
    defer allocator.free(launch_path);
    try installExecutableScript(launch_path, launch_script, "warning: could not chmod padctl-reconnect-launch\n");
}

/// Outcome of the start phase, fed back to the post-install verify gate so it
/// can tell a genuine crash-loop (start ran on a live bus, daemon never
/// answered) from a headless/boot-before-login install (the user bus is not
/// live yet, the service is enabled and will start at next login).
pub const StartOutcome = struct {
    /// True when a `systemctl --user start` was requested (not --no-start and
    /// the bus plan was not .skip).
    start_attempted: bool = false,
    /// True only when `systemctl --user start` actually ran and exited 0,
    /// i.e. the user bus was reachable and the unit was launched.
    start_ran: bool = false,
};

// Manage the systemd units. The caller reloads the udev ruleset and applies
// driver state first, so the service starts against a device already in its
// final driver state.
pub fn runSystemctlUnits(plan: *const InstallPlan) StartOutcome {
    if (plan.systemctl_plan.mode == .skip) {
        var groups: [3][]const []const u8 = undefined;
        var n: usize = 0;
        groups[n] = &.{"daemon-reload"};
        n += 1;
        if (!plan.opts.no_enable) {
            groups[n] = &.{ "enable", "padctl.service" };
            n += 1;
        }
        if (!plan.opts.no_start) {
            groups[n] = &.{ "start", "padctl.service" };
            n += 1;
        }
        printSkipSystemctlNoteFor(groups[0..n]);
        return .{};
    }
    runSystemctlUser(&.{"daemon-reload"});
    if (!plan.opts.no_enable) {
        _ = runSystemctlUserWarn(&.{ "enable", "padctl.service" });
    }
    if (plan.opts.no_start) return .{};
    const ran = runSystemctlUserWarn(&.{ "start", "padctl.service" });
    return .{ .start_attempted = true, .start_ran = ran };
}
