#!/bin/sh
set -e
if [ "$1" = "remove" ] || [ "$1" = "purge" ]; then
    if [ -d /run/systemd/system ]; then
        systemctl stop padctl.service padctl-resume.service || true
        systemctl disable padctl.service padctl-resume.service || true
    fi
fi
