pub const ButtonId = enum {
    A,
    B,
    X,
    Y,
    LB,
    RB,
    LT,
    RT,
    Start,
    Select,
    Home,
    Capture,
    LS,
    RS,
    DPadUp,
    DPadDown,
    DPadLeft,
    DPadRight,
    M1,
    M2,
    M3,
    M4,
    Paddle1,
    Paddle2,
    Paddle3,
    Paddle4,
    TouchPad,
    Mic,
};

pub const GamepadState = struct {
    ax: i16 = 0,
    ay: i16 = 0,
    rx: i16 = 0,
    ry: i16 = 0,
    lt: u8 = 0,
    rt: u8 = 0,
    dpad_x: i8 = 0,
    dpad_y: i8 = 0,
    buttons: u32 = 0,
    gyro_x: i16 = 0,
    gyro_y: i16 = 0,
    gyro_z: i16 = 0,
    accel_x: i16 = 0,
    accel_y: i16 = 0,
    accel_z: i16 = 0,
};

pub const GamepadStateDelta = struct {
    ax: ?i16 = null,
    ay: ?i16 = null,
    rx: ?i16 = null,
    ry: ?i16 = null,
    lt: ?u8 = null,
    rt: ?u8 = null,
    dpad_x: ?i8 = null,
    dpad_y: ?i8 = null,
    buttons: ?u32 = null,
    gyro_x: ?i16 = null,
    gyro_y: ?i16 = null,
    gyro_z: ?i16 = null,
    accel_x: ?i16 = null,
    accel_y: ?i16 = null,
    accel_z: ?i16 = null,
};
